using '../main.bicep'

param environmentName = 'test'
param location = 'eastus2'
param functionAppName = 'sas-email-fwd-test-func'
param functionPlanName = 'sas-email-fwd-test-plan'
param storageAccountName = 'sasemailfwdtestst'
param applicationInsightsName = 'sas-email-fwd-test-ai'
param logAnalyticsWorkspaceName = 'sas-email-fwd-test-law'
param keyVaultName = 'sas-email-test-kv'
param cosmosAccountName = 'sas-email-fwd-test-cosmos'
param cosmosAccountResourceGroupName = 'IacReferenceForCodeAlong'
param cosmosDatabaseName = 'EmailForwarding'
param cosmosContainerName = 'ContactInfoAndRequests'
param emailRetryTimeZone = 'Eastern Standard Time'
